swagger: '2.0'
info:
  description: 'GLPro API Document'
  version: '1.0.0'
  title: 'GLPro API'
paths:
  /area/{'areaid'}:
    get:
      summary: '地区詳細API'
      description: '指定さてた地区idの地区名、地区の詳細情報を返します。'
      parameters:
        - name: 'area_id'
          in: 'path'
          description: '取得したい地区のID'
          required: true
          type: 'number'
      responses:
        200:
          description: '成功時のレスポンス'
          schema:
            type: object
            properties:
              area:
                $ref: '#/definitions/area_name'
              area_details:
                $ref: '#/definitions/area_details'
              category:
                $ref: '#/definitions/category'
  /review/create:
    post:
      summary: '新規レビュー作成API'
      description: 'リクエストされたパラメータのレビューを作成します。'
      parameters:
        - in: body
          name: reviewParam
          description: オブジェクトのキーと型
          schema:
            type: object
            properties:
              user_id:
                type: number
              area_id:
                type: number
              category_id:
                type: number
              review_content:
                type: string
                example: 'content'
              evaluation:
                type: number
      responses:
        200:
          description: 'message : success'
        400:
          description: 'message : failure, error: e'
definitions:
  area_name:
    type: 'string'
    example: '渋谷区'
  area_details:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int64'
      user_Id:
        type: 'integer'
        format: 'int64'
      area_Id:
        type: 'integer'
        format: 'int64'
      category_id:
        type: 'integer'
        format: 'int64'
      review_content:
        type: 'string'
        example: 'content'
      evaluation:
        type: 'integer'
        format: 'int64'
      created_at:
        type: 'string'
        example: '20xx-xx-xx'
        format: 'date'
  category:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int64'
      category_name:
        type: 'string'
        example: '治安'
