swagger: '2.0'
info:
  description: 'GLPro API Document'
  version: '1.0.0'
  title: 'GLPro API'
paths:
  /area/{'areaid'}:
    get:
      summary: '地区詳細API'
      description: '指定さてた地区idの地区名、地区の詳細情報を返します。'
      parameters:
        - name: 'area_id'
          in: 'path'
          description: '取得したい地区のID'
          required: true
          type: 'number'
      responses:
        200:
          description: '成功時のレスポンス'
          schema:
            $ref: '#/definitions/area_details'

definitions:
  area_name:
    type: 'object'
    properties:
      name:
        type: 'string'
        example: 'name'
    items:
      $ref: '#/definitions/area_details' # Storeを呼び出す
  area_details:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int64'
      user_Id:
        type: 'integer'
        format: 'int64'
      area_Id:
        type: 'integer'
        format: 'int64'
      category_id:
        type: 'integer'
        format: 'int64'
      review_content:
        type: 'string'
        example: 'content'
      evaluation:
        type: 'integer'
        format: 'int64'
      created_at:
        type: 'string'
        example: '20xx-xx-xx'
        format: 'date'
